version: '3.8'
services:
  db-staging:
    image: mysql:8.0
    container_name: wordpress-db-staging
    restart: always
    networks:
      - default
    volumes:
      - wordpress_staging_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress-staging:
    image: ${ACR_LOGIN_SERVER}/my-wordpress:${IMAGE_TAG}
    container_name: wordpress-staging
    restart: always
    networks:
      - default
      - caddy_network # --- FIX: Also connects to the shared Caddy network ---
    volumes:
      - wordpress_staging_uploads:/var/www/html/wp-content/uploads
    environment:
      WORDPRESS_DB_HOST: db-staging:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      - db-staging

volumes:
  wordpress_staging_db_data: {}
  wordpress_staging_uploads: {}

networks:
  caddy_network:
    external: true