name: Build and Deploy WordPress

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v3

      - name: 'Login to Azure Container Registry'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: 'Determine Environment and Tag'
        id: det-env
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "env_file=live.env" >> $GITHUB_OUTPUT
            echo "compose_file=docker-compose-live.yml" >> $GITHUB_OUTPUT
            echo "project_dir=wordpress-live" >> $GITHUB_OUTPUT
          else
            echo "env_file=staging.env" >> $GITHUB_OUTPUT
            echo "compose_file=docker-compose-staging.yml" >> $GITHUB_OUTPUT
            echo "project_dir=wordpress-staging" >> $GITHUB_OUTPUT
          fi
          echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: 'Build and Push to Azure Container Registry'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/my-wordpress:${{ steps.det-env.outputs.tag }}

      - name: 'Deploy to Server'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Enable command printing for full visibility
            set -x
            # Exit immediately if a command exits with a non-zero status.
            set -e

            # Navigate to the correct project directory
            cd ~/${{ steps.det-env.outputs.project_dir }}

            # Update the IMAGE_TAG in the .env file on the server
            sed -i "s/^IMAGE_TAG=.*/IMAGE_TAG=${{ steps.det-env.outputs.tag }}/" ${{ steps.det-env.outputs.env_file }}

            # --- THE FIX IS HERE ---
            # Manually export the variables from the .env file into the shell's environment
            set -o allexport
            source ${{ steps.det-env.outputs.env_file }}
            set +o allexport
            # --- END OF FIX ---

            # Now run docker compose. It will automatically find the variables in the environment.
            echo "Pulling new image with fully resolved name..."
            docker compose -f ${{ steps.det-env.outputs.compose_file }} pull

            echo "Restarting services..."
            docker compose -f ${{ steps.det-env.outputs.compose_file }} up -d --remove-orphans
            
            echo "✅ Deployment successful!"
