name: Build and Deploy WordPress

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v3

      - name: 'Login to Azure Container Registry'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: 'Determine Environment and Tag'
        id: det-env
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "env_file=live.env" >> $GITHUB_OUTPUT
            echo "compose_file=docker-compose-live.yml" >> $GITHUB_OUTPUT
            echo "project_dir=wordpress-live" >> $GITHUB_OUTPUT
          else
            echo "env_file=staging.env" >> $GITHUB_OUTPUT
            echo "compose_file=docker-compose-staging.yml" >> $GITHUB_OUTPUT
            echo "project_dir=wordpress-staging" >> $GITHUB_OUTPUT
          fi
          echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: 'Build and Push to Azure Container Registry'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/my-wordpress:${{ steps.det-env.outputs.tag }}

      - name: 'Deploy to Server'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Exit on error and print commands
            set -ex

            # Login to ACR (we know this works)
            echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

            # Navigate to the project directory
            cd ~/${{ steps.det-env.outputs.project_dir }}

            # --- THE FINAL FIX ---
            # Dynamically create a clean .env file on the server using secrets.
            # This avoids all local file formatting issues.
            echo "--- Creating fresh .env file on the server ---"
            cat > ${{ steps.det-env.outputs.env_file }} << EOF
            MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
            MYSQL_USER=${{ secrets.MYSQL_USER }}
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            ACR_LOGIN_SERVER=${{ secrets.ACR_LOGIN_SERVER }}
            IMAGE_TAG=${{ steps.det-env.outputs.tag }}
            EOF
            
            # Use the new, auto-generated .env file to run the deployment
            echo "--- Restarting services with auto-generated config ---"
            docker compose -f ${{ steps.det-env.outputs.compose_file }} pull
            docker compose -f ${{ steps.det-env.outputs.compose_file }} up -d --remove-orphans

            echo "✅ Deployment successful!"
