name: Secret Debug Workflow

on:
  push:
    branches:
      - main

jobs:
  debug-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check if Secrets are Accessible'
        run: |
          echo "SERVER_HOST value is: ${{ secrets.SERVER_HOST }}"
          echo "SERVER_USERNAME value is: ${{ secrets.SERVER_USERNAME }}"
          
          if [ -n "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "✅ SSH_PRIVATE_KEY is present and not empty."
          else
            echo "❌ ERROR: SSH_PRIVATE_KEY is EMPTY or not found."
          fi
          
          if [ -n "${{ secrets.ACR_LOGIN_SERVER }}" ]; then
            echo "✅ ACR_LOGIN_SERVER is present and not empty."
          else
            echo "❌ ERROR: ACR_LOGIN_SERVER is EMPTY or not found."
          fi
